apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clotho-config
data:
  clotho-config.yaml: |
    log-level: {{ .Values.logLevel }}
    check-existing: {{ .Values.checkExisting }}
    health-checker:
{{ toYaml .Values.healthChecker | indent 6 }}
    server:
      port: {{ .Values.server.port }}
      company-domain: {{ .Values.server.companyDomain }}
      namespace: {{ .Release.Namespace }}
      {{ if eq .Values.service.name "" -}}
      service: {{ include "clotho.fullname" . }}
      {{ else -}}
      service: {{ .Values.service.name }}
      {{ end -}}
      ca-cert-path: /tls/ca-cert
      cert-path: /tls/server-cert
      key-path: /tls/server-key
    rules:
    - registration:
        name: add-name-label-to-namespaces
        targets:
        - api-groups:
          - ""
          api-versions:
          - v1
          resources:
          - namespaces
        failure-policy: Ignore
       payload:
         additions:
           labels:
             name: '{{ index . "metadata.name" }}'
