apiVersion: v1
kind: ConfigMap
metadata:
  name: clotho-config
  namespace: clotho
data:
  clotho-config.yaml: |
    log-level: info
    check-existing: false
    health-checker:
      port: 9999
      path: /am-i-healthy
    server:
      port: 8443
      namespace: clotho
      service: clotho
      ca-cert-path: /tls/ca-cert
      cert-path: /tls/server-cert
      key-path: /tls/server-key
    rules:
    - registration:
        name: add-name-label-to-namespaces
        targets:
        - api-groups:
          - ""
          api-versions:
          - v1
          resources:
          - namespaces
        failure-policy: Ignore
      payload:
        additions:
          labels:
            name: '{{ index . "metadata.name" }}'
